name: CI
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Download alpine-chroot-install
        run: |
          wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.13.3/alpine-chroot-install
          echo 'c3005e323029637db20ec9595243ac94bb9b2226  alpine-chroot-install' | sha1sum -c
          chmod +x alpine-chroot-install

      - name: Install latest stable Alpine Linux
        run: |
          sudo ./alpine-chroot-install \
            -b latest-stable \
            -p 'asciidoctor make tree zsh'

      - name: make check
        run: /alpine/enter-chroot -u $USER make check

      - name: make install
        run: |
          /alpine/enter-chroot -u $USER make install DESTDIR=dest
          tree dest/
