name: CI
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install latest stable Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          packages: >
            asciidoctor
            make
            tree
            zsh

      - name: make check
        run: make check
        shell: alpine.sh {0}

      - name: make install
        run: |
          make install DESTDIR=dest
          tree dest/
        shell: alpine.sh {0}
